create table if not exists public.songs (
    song_id text primary key,
    filename text not null,
    storage_path text not null unique,
    sha256 text not null unique,
    title text not null,
    artist text not null default '',
    enabled boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.ratings (
    id bigint generated by default as identity primary key,
    song_id text not null references public.songs(song_id) on delete cascade,
    rater_id text not null check (char_length(rater_id) between 2 and 40),
    rater_key text not null check (char_length(rater_key) between 2 and 40),
    instrument text not null,
    experience_years double precision not null check (experience_years between 0 and 80),
    difficulty text not null check (difficulty in ('Beginner', 'Intermediate', 'Advanced')),
    confidence integer not null check (confidence between 1 and 5),
    comment text not null default '' check (char_length(comment) <= 1000),
    rated_at timestamptz not null default now(),
    unique (song_id, rater_key)
);

create index if not exists ratings_song_id_index on public.ratings (song_id);
create index if not exists ratings_rater_key_index on public.ratings (rater_key);

alter table public.songs enable row level security;
alter table public.ratings enable row level security;

revoke all on table public.songs from anon, authenticated;
revoke all on table public.ratings from anon, authenticated;
grant all on table public.songs to service_role;
grant all on table public.ratings to service_role;
grant usage, select on sequence public.ratings_id_seq to service_role;
